### ISSUE TITLE
Append Function and ! Guidlines

### ISSUE THREAD

**Issue by JosephTomlinson** [christiangil/GP-Research#1]
https://github.com/christiangil/GP-Research/blob/ea9d11036c7cdaae54714d99c39fa1fdb88fa384/julia/src/general_functions.jl#L9-L15

Is there an explicit need for this function? It not only breaks the generally useful guidelines of having an ! for a function that modifies its arguments, but in my experience doing something like
`append!(a, [b1,b2,b3,b4])`
is generally faster anyway.

**Comment by JosephTomlinson** [comment]
Just as a quick addition. I know it can be a little annoying but another function is missing the !
https://github.com/christiangil/GP-Research/blob/3812c3514050ea12349100cf6ee9323b28ce81d1/julia/src/general_functions.jl#L110-L114

I know for internal functions it can seem to be a bit pointless, but I find that distinguishing clearly between functions that modify input and functions that don't can often help me debug more quickly.

**Comment by christiangil** [comment]
Neither of these functions are ever used, but I agree I should stick to conventions here.

Renamed chop_array to chop_array! and append to multiple_append!

The multiple_append! function is meant to append multiple lists with one function call. For example, this code breaks
```julia
a=[1.]
b=[2.]
c=[3.]
append!(a,[b,c])
```
but this doesn't
```julia
a=[1.]
b=[2.]
c=[3.]
multiple_append!(a,b,c)
```
