### ISSUE TITLE
partialsortperm

### ISSUE THREAD

**Issue by eford** [christiangil/GP-Research#12]
https://github.com/christiangil/GP-Research/blob/7d26b0afc9cfe60c9f2345b8b9f41c3a1aefec22/julia/src/general_functions.jl#L218-L225
[partialsortperm](https://docs.julialang.org/en/v1/base/sort/#Base.Sort.partialsortperm)

**Comment by christiangil** [comment]
Cool thanks! Nice to see the computer scientists making useful functions
