### ISSUE TITLE
Why backwards?  

### ISSUE THREAD

**Issue by eford** [christiangil/GP-Research#19]
https://github.com/christiangil/GP-Research/blob/7d26b0afc9cfe60c9f2345b8b9f41c3a1aefec22/julia/src/GP_functions.jl#L488-L491

**Comment by christiangil** [comment]
It was just faster to write it that way. I am applying the same prior to all of the length scales which are all at the end of the total_hyperparamters list.

**Comment by eford** [comment]
Oh, I see.  That makes sense.
You might find it useful to make accessor/mutator functions that allow you to access the hyper parameters by name/natural number rather than by array index.
