### ISSUE TITLE
Potential Bug in \phi_approx

### ISSUE THREAD

**Issue by JosephTomlinson** [christiangil/GP-Research#2]
https://github.com/christiangil/GP-Research/blob/ea9d11036c7cdaae54714d99c39fa1fdb88fa384/julia/src/RV_functions.jl#L61-L83
So I'm not sure if I'm just misunderstanding something here but it seems that in this part
https://github.com/christiangil/GP-Research/blob/ea9d11036c7cdaae54714d99c39fa1fdb88fa384/julia/src/RV_functions.jl#L71-L79
You will just always get `term_list = [2 * e - 1/4, 0...]` because every `e_list` is always 0.

**Comment by JosephTomlinson** [comment]
I think this is a good opportunity for an additional test. I briefly skimmed over the tests you have and I didn't see anything that I though would call this (admittedly I didn't dig into every function to check).

If, as I suspect, \phi_approx is an approximation to \phi (otherwise that itself is a function naming issue) then maybe some test of where you expect some reasonable agreement between the two would be a good addition.

**Comment by christiangil** [comment]
Good catch changed
```julia
e_list = zeros(7)
e_list = [e_list[i] * e for i in 1:7]
```
to
```julia
e_list = [e ^ i for i in 1:7]
```

there actually is a test already in tests.jl
https://github.com/christiangil/GP-Research/blob/ea9d11036c7cdaae54714d99c39fa1fdb88fa384/julia/test/tests.jl#L38-L43

I'll lower the rtol to make sure its actually working
I've also added tests to make sure that the true anomalies are different from the mean anomaly

```julia
@testset "true anomaly" begin
    # see if the low eccentricity approximation is working
    test_time = rand()
    P=2.
    ecc=0.01
    @test isapprox(ϕ(test_time, P; e=ecc), ϕ_approx(test_time, P; e=ecc); rtol=1e-3)
    @test ϕ(test_time, P; e=ecc)!=mean_anomaly(test_time, P)
    @test ϕ_approx(test_time, P; e=ecc)!=mean_anomaly(test_time, P)
    println()
end
```
