### ISSUE TITLE
General Comments on Float64 Usage

### ISSUE THREAD

**Issue by JosephTomlinson** [christiangil/GP-Research#3]
I'm not going to reference any specific code for this issue (as there are many examples) but you often use Float64 in your function definitions when many times the function is perfectly suitable for any real numbers.

I recommend switching many of your function definitions (perhaps all of them?) to use Real instead. 
This will not only allow you to potentially use integers should you forget to type 1.0 instead of 1, but would be very useful if you for example wanted to implement this on GPUs where Float32 is often used without having to go and change stuff then.

**Comment by christiangil** [comment]
Good comment. It is done.
