### ISSUE TITLE
Minor Performance Boost in find_modes

### ISSUE THREAD

**Issue by JosephTomlinson** [christiangil/GP-Research#4]
https://github.com/christiangil/GP-Research/blob/ea9d11036c7cdaae54714d99c39fa1fdb88fa384/julia/src/general_functions.jl#L194-L217

I've found that the find_modes function can be partial rewritten to get about a 5% performance increase. It is pretty minor, and I'm unsure how slow this function is compared to whatever else your doing (it is likely negligible) but I think the faster version is slightly more readable so here is my suggestion.

Go from
```julia
    # creating boolean list for inds at modes
    mode_inds = [(data[i]>=data[i-1]) & (data[i]>=data[i+1]) for i in 2:(length(data)-1)]
    prepend!(mode_inds, data[1]>data[2])
    append!(mode_inds, data[end]>data[end-1])

    # get data values at each mode
    data_modes = data[mode_inds]

    # get index values of modes in the original list
    mode_inds = collect(1:length(data))[mode_inds]
```
to
```julia
    # creating index list for inds at modes
    mode_inds = [i for i in 2:(length(data)-1) if (data[i]>=data[i-1]) & (data[i]>=data[i+1])]
    if data[1] > data[2]
        append!(mode_inds, 1)
    end
    if data[end] > data[end-1]
        append!(mode_inds, length(data))
    end

    # get data values at each mode
    data_modes = data[mode_inds]
```
This avoids needing to calculate a Boolean array and jumps right to getting the index array, which you need later on in the code anyway.

**Comment by christiangil** [comment]
Cool thanks!
